# Generated by Django 4.1.1 on 2022-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_newuser_remove_profile_id_user_remove_profile_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
